test_that("tidy, glance, and augment summarise a fit", {
  dat <- norm_simulate(200, seed = 61)
  dat$marker_bad <- 1
  fit <- norm_fit(simple_spec(), data = dat, outcomes = c("y", "marker_01", "marker_bad"))
  td <- tidy(fit)
  expect_s3_class(td, "tbl_df")
  expect_equal(td$outcome, c("y", "marker_01", "marker_bad"))
  expect_equal(td$status, c("ok", "ok", "insufficient_variation"))
  expect_equal(td$family, rep("gaussian", 3))
  expect_equal(td$n[1:2], c(200L, 200L))
  expect_true(is.na(td$n[[3]]))
  expect_true("edf_s(age)" %in% names(td))
  expect_true(all(td[["edf_s(age)"]][1:2] >= 1))
  expect_true(all(td$edf[1:2] > td[["edf_s(age)"]][1:2]))
  expect_equal(names(td)[[length(td)]], "message")
  expect_match(td$message[[3]], "variation")

  gl <- glance(fit)
  expect_equal(nrow(gl), 1L)
  expect_equal(gl$n_outcomes, 3L)
  expect_equal(gl$n_ok, 2L)
  expect_false(gl$adapted)
  expect_equal(gl$covariates, "age, sex")

  new <- dat[1:5, ]
  au <- augment(fit, new, uncertainty = "conditional")
  expect_equal(nrow(au), 5L)
  expect_true(all(c(".z_y", ".centile_y", ".z_marker_01", ".z_marker_bad", ".support") %in% names(au)))
  expect_equal(names(au)[seq_along(new)], names(new))
  sc <- predict(fit, newdata = new, uncertainty = "conditional")
  expect_equal(au$.z_y, sc$z[sc$.outcome == "y"])
  expect_equal(au$.centile_marker_01, sc$centile[sc$.outcome == "marker_01"])
  expect_true(all(is.na(au$.z_marker_bad)))
  expect_equal(au$.support, norm_support(fit, new)$support)
})

test_that("glance summarises an assessment in one row", {
  train <- norm_simulate(250, seed = 62)
  test <- norm_simulate(120, seed = 63)
  fit <- norm_fit(simple_spec(), data = train, outcomes = c("y", "marker_01"))
  a <- norm_assess(fit, newdata = test)
  gl <- glance(a)
  expect_equal(nrow(gl), 1L)
  expect_equal(gl$n, 120L)
  expect_equal(gl$n_outcomes, 2L)
  expect_equal(gl$crps, mean(a$overall$crps))
  expect_equal(gl$var_z, mean(a$marginal$var_z))
  expect_false(gl$in_sample)
})

test_that("norm_joint accepts augment output", {
  dat <- norm_simulate(300, seed = 64)
  fit <- norm_fit(simple_spec(), data = dat[1:200, ], outcomes = c("y", "marker_01"))
  au <- augment(fit, dat[201:300, ], uncertainty = "conditional")
  j_wide <- norm_joint(au)
  sc <- predict(fit, newdata = dat[201:300, ], uncertainty = "conditional")
  j_long <- norm_joint(sc)
  expect_equal(j_wide$outcomes, c("y", "marker_01"))
  expect_equal(j_wide$correlation, j_long$correlation)
  expect_equal(j_wide$reference$joint_z, j_long$reference$joint_z)
  pw <- predict(j_wide, augment(fit, dat[1:10, ], uncertainty = "conditional"))
  pl <- predict(j_long, predict(fit, newdata = dat[1:10, ], uncertainty = "conditional"))
  expect_equal(pw$joint_centile, pl$joint_centile)
})
